#!/usr/bin/env python3
"""Package the generated static site as a Cloudflare Worker for Sites."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
PUBLIC = ROOT / "public"
OUTPUT = ROOT / "dist" / "server" / "index.js"
FILES = {
    "/index.html": ("index.html", "text/html; charset=utf-8"),
    "/styles.css": ("styles.css", "text/css; charset=utf-8"),
    "/app.js": ("app.js", "text/javascript; charset=utf-8"),
    "/papers-data.js": ("papers-data.js", "text/javascript; charset=utf-8"),
}


def main() -> None:
    assets = {
        route: {
            "body": (PUBLIC / filename).read_text(encoding="utf-8"),
            "contentType": content_type,
        }
        for route, (filename, content_type) in FILES.items()
    }
    payload = json.dumps(assets, ensure_ascii=False, separators=(",", ":"))
    worker = f"""// Generated by build_sites_worker.py. Do not edit directly.
const files = Object.freeze({payload});

export default {{
  async fetch(request) {{
    const url = new URL(request.url);
    const path = url.pathname === "/" ? "/index.html" : url.pathname;
    const file = files[path];
    if (!file) {{
      return new Response("Not Found", {{
        status: 404,
        headers: {{ "content-type": "text/plain; charset=utf-8" }},
      }});
    }}
    const cacheControl = path === "/papers-data.js"
      ? "no-cache"
      : "public, max-age=3600";
    return new Response(file.body, {{
      headers: {{
        "content-type": file.contentType,
        "cache-control": cacheControl,
        "x-content-type-options": "nosniff",
        "referrer-policy": "strict-origin-when-cross-origin",
      }},
    }});
  }},
}};
"""
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(worker, encoding="utf-8")
    print(f"Built {OUTPUT} with {len(assets)} embedded assets.")


if __name__ == "__main__":
    main()
